### ISSUE TITLE
Need to check file format 

### ISSUE THREAD

**Issue by abdesslem** [hgn/captcp#29]
python captcp.py statistic file.txt
# captcp 2010-2013 Hagen Paul Pfeifer and others (c)
# http://research.protocollabs.com/captcp/
Traceback (most recent call last):
  File "captcp.py", line 5301, in <module>
    sys.exit(captcp.run())
  File "captcp.py", line 5269, in run
    pcap_parser = PcapParser(self.pcap_file_path, self.pcap_filter)
  File "captcp.py", line 534, in __init__
    self.pc = dpkt.pcap.Reader(self.pcap_file)
  File "/usr/lib/pymodules/python2.7/dpkt/pcap.py", line 97, in __init__
    self.__fh = FileHdr(buf)
  File "/usr/lib/pymodules/python2.7/dpkt/dpkt.py", line 75, in __init__
    raise NeedData
dpkt.dpkt.NeedData

It can be checked with "FileHdr" class in the dpkt module.

**Comment by hgn** [comment]
Catching dpkt.dpkt.NeedData and printing a nice user info message? I am open to implement something else too - what did you expected?
